files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero:
    - 2
    - convention: zero
  brace-style:
    - 2
    - allow-single-line: true
  class-name-format: 0
  clean-import-paths:
    - 2
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks: 2
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  hex-length: 2
  hex-notation:
    - 2
    - style: lowercase
  id-name-format: 0
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: false
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-keyword: 2
  no-color-literals: 0
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties: 1
  no-empty-rulesets: 2
  no-ids: 1
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 2
    - extra-properties: []
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 2
  no-url-protocols: 0
  no-vendor-prefixes: 0
  placeholder-in-extend: 1
  placeholder-name-format: 0
  property-sort-order: 2
  property-units:
    - 1
    - global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - '%'
      per-property: {}
  quotes:
    - 2
    - style: single
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma: 2
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon: 2
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property: 0
  variable-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  zero-unit: 2
