version: '3'

volumes:
  build:
  pg-data:

services:
  traefik:
    image: traefik:1.1.2
    volumes:
      - ./etc/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'
      - '8080:8080'

  postgres:
    image: postgres:9.6.2
    volumes:
      - pg-data:/var/lib/postgresql/data

  cogs: &shared
    image: quay.io/caseywebdev/turbo-car-club:2c66a1278eb32de90dca4ca54a9b02b0710ca7c6
    volumes:
      - ./.eslintrc:/code/.eslintrc
      - ./.stylelintrc:/code/.stylelintrc
      - ./bin:/code/bin
      - ./etc:/code/etc
      - ./package.json:/code/package.json
      - ./src:/code/src
      - build:/code/build
    command: bin/watch-build

  livereload:
    <<: *shared
    command: bin/livereload
    labels:
      traefik.enable: 'true'
      traefik.port: '80'
      traefik.frontend.rule: Host:livereload.dev.turbocarclub.com

  client:
    <<: *shared
    environment:
      LIVERELOAD_URL: http://livereload.dev.turbocarclub.com
    command: bin/client
    labels:
      traefik.enable: 'true'
      traefik.port: '80'
      traefik.frontend.rule: Host:www.dev.turbocarclub.com

  signal:
    <<: *shared
    command: bin/watch-signal
    labels:
      traefik.enable: 'true'
      traefik.port: '80'
      traefik.frontend.rule: Host:signal.dev.turbocarclub.com
    depends_on:
      - postgres
