data:
  image: &image quay.io/caseywebdev/turbo-car-club:0.0.28
  volumes:
    - ./.eslintrc:/code/.eslintrc
    - ./.sass-lint.yml:/code/.sass-lint.yml
    - ./bin:/code/bin
    - ./cogs-client.js:/code/cogs-client.js
    - ./cogs-server.js:/code/cogs-server.js
    - ./Makefile:/code/Makefile
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./package.json:/code/package.json
    - ./src:/code/src
    - /code/build
    - /code/node_modules
  command: 'true'

dbdata:
  image: busybox:1.24.1
  volumes:
    - /var/lib/postgresql/data
  command: 'true'

postgres:
  image: postgres:9.4.5
  volumes_from:
    - dbdata
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  ports:
    - '5432'

nginx:
  image: nginx:1.9.5
  volumes_from:
    - data
  ports:
    - '80:80'

cogs-client: &shared
  image: *image
  volumes_from:
    - data
  environment:
    SIGNAL_URL: ws://docker:1337
  command: make cogs-client-w

cogs-server:
  <<: *shared
  command: make cogs-server-w

livereload:
  <<: *shared
  ports:
    - '35729:35729'
  command: bin/livereload

signal:
  <<: *shared
  links:
    - postgres
  ports:
    - '1337:80'
  environment:
    KEY: foo
    MAIL_ENABLED: 0
    MAIL_FROM_NAME: Turbo Car Club
    MAIL_FROM_ADDRESS: support@turbocarclub.com
    POSTGRES_URL: pg://postgres:postgres@postgres/postgres
    CLIENT_URL: http://docker
  command: make signal-w

larry:
  <<: *shared
  links:
    - signal
  environment:
    KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImlhdCI6MTQ1NjU3NzczMCwic3ViIjoiYXV0aCJ9.s4NSGM67mLtr177ND3WsMObZT3QVJRD0chjDDf8aPe0
    NAME: Larry
    SIGNAL_URL: ws://signal
  command: make host-w

curly:
  <<: *shared
  links:
    - signal
  environment:
    KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImlhdCI6MTQ1NjU3NzczMCwic3ViIjoiYXV0aCJ9.s4NSGM67mLtr177ND3WsMObZT3QVJRD0chjDDf8aPe0
    NAME: Curly
    SIGNAL_URL: ws://signal
  command: make host-w

mo:
  <<: *shared
  links:
    - signal
  environment:
    KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImlhdCI6MTQ1NjU3NzczMCwic3ViIjoiYXV0aCJ9.s4NSGM67mLtr177ND3WsMObZT3QVJRD0chjDDf8aPe0
    NAME: Mo
    SIGNAL_URL: ws://signal
  command: make host-w
