version: '3'

volumes:
  build:
  pg-data:

services:
  postgres:
    image: postgres:9.6.2
    volumes:
      - pg-data:/var/lib/postgresql/data

  cogs: &shared
    image: quay.io/coderiety/turbo-car-club:2f30289456ea6809cf879bb3a139008fc2e24a61
    volumes:
      - ./.eslintrc:/code/.eslintrc
      - ./.stylelintrc:/code/.stylelintrc
      - ./bin:/code/bin
      - ./etc:/code/etc
      - ./package.json:/code/package.json
      - ./src:/code/src
      - build:/code/build
    command: bin/watch-build

  livereload:
    <<: *shared
    command: bin/livereload
    ports:
      - 8081:80

  client:
    <<: *shared
    command: bin/client
    environment:
      LIVERELOAD_URL: http://localhost:8081
    ports:
      - 80:80

  signal:
    <<: *shared
    command: bin/watch-signal
    depends_on:
      - postgres
    ports:
      - 8080:80
