version: '2'

services:
  persisted-data:
    image: busybox:1.24.1
    volumes:
      - /etc/ssl/private
      - /var/lib/postgresql/data
    command: 'true'

  ephemeral-data:
    image: &image quay.io/caseywebdev/turbo-car-club:d9eece4240dcdbd82c37e45ecd9081c559685e27
    volumes:
      - ./.eslintrc:/code/.eslintrc
      - ./.stylelintrc:/code/.stylelintrc
      - ./bin:/code/bin
      - ./etc:/code/etc
      - ./package.json:/code/package.json
      - ./src:/code/src
      - /code/build
      - /code/node_modules
    command: 'true'

  consul:
    image: quay.io/caseywebdev/consul:836521c3324593cd3abeafb27c1ade813ae15a67
    dns: &dns 172.17.0.1
    dns_search: service.consul
    ports:
      - '172.17.0.1:53:53/udp'
    command: -dev

  postgres:
    image: quay.io/caseywebdev/postgres:a979e843fdd850c2e72d93cb5fff994d91d7e2a3
    dns: *dns
    dns_search: service.consul
    volumes_from:
      - persisted-data
    depends_on:
      - consul

  cogs-client: &shared
    image: *image
    dns: *dns
    dns_search: service.consul
    volumes_from:
      - persisted-data
      - ephemeral-data
    command: bin/watch-build-client
    depends_on:
      - consul
    environment:
      LIVERELOAD_SERVER_NAME: livereload.dev.turbocarclub.com
      LIVERELOAD_URL: https://livereload.dev.turbocarclub.com
      CONSUL_AUTH: foo:bar
      CONSUL_SERVER_NAME: consul.dev.turbocarclub.com
      SIGNAL_SERVER_NAME: signal.dev.turbocarclub.com

  cogs-server:
    <<: *shared
    command: bin/watch-build-server

  livereload:
    <<: *shared
    command: bin/livereload

  lb:
    <<: *shared
    ports:
      - '80:80'
      - '443:443'
    command: bin/lb

  signal:
    <<: *shared
    command: bin/watch-signal
    depends_on:
      - postgres
    command: bin/signal
