client:
  image: quay.io/turbocarclub/client:latest
  volumes:
    - ./tmp/client/build:/code/build
    - ./src:/code/src
    - ./src/client/package.json:/code/package.json
  environment:
    MINIFY: 0
  command: make -f src/client/Makefile dev

host:
  image: quay.io/turbocarclub/host:latest
  volumes:
    - ./src:/code/src
    - ./src/host/package.json:/code/package.json
  ports:
    - '1338:80'
  links:
    - signal
  environment:
    SIGNAL_URL: ws://signal
  command: make -f src/host/Makefile dev

signal:
  image: quay.io/turbocarclub/signal:latest
  volumes:
    - ./src:/code/src
    - ./src/signal/package.json:/code/package.json
  ports:
    - '1337:80'
  command: make -f src/signal/Makefile dev

nginx:
  image: nginx:1.9.5
  volumes:
    - ./tmp/client/build:/usr/share/nginx/html
  ports:
    - '80:80'
