postgres:
  image: postgres:9.4.5
  volumes:
    - ./postgres:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  ports:
    - '5432'

nginx:
  image: nginx:1.9.5
  volumes:
    - ./var/build/client:/usr/share/nginx/html
  ports:
    - '80:80'

cogs-client: &shared
  image: quay.io/turbocarclub/turbo-car-club:0.0.7
  volumes:
    - .:/code
  environment:
    SIGNAL_URL: ws://docker:1337
  command: make cogs-client-w

cogs-server:
  <<: *shared
  command: make cogs-server-w

signal:
  <<: *shared
  links:
    - postgres
  ports:
    - '1337:80'
  environment:
    KEY: foo
    MAIL_ENABLED: 0
    MAIL_FROM_NAME: Turbo Car Club
    MAIL_FROM_ADDRESS: support@turbocarclub.com
    POSTGRES_URL: pg://postgres:postgres@postgres/postgres
    CLIENT_URL: http://docker
  command: make signal-w

host:
  <<: *shared
  links:
    - signal
  ports:
    - '1338:80'
  environment:
    KEY: qrzeTOFGCcBcVmbnchSncrHo4sEpDDmVXSOof2WqoaRbWyJob3N0IiwxNDQ1Nzk4OTUzNTAyXSx7InVzZXJJZCI6MSwicmVnaW9uIjoiTG9jYWwiLCJuYW1lIjoiSG9zdCIsInVybCI6IndzOi8vZG9ja2VyOjEzMzgifV0=
    SIGNAL_URL: ws://signal
  command: make host-w
