data:
  image: &image quay.io/caseywebdev/turbo-car-club:0ec52eab581acf673c96e4a038ec54ef849c7445
  volumes:
    - ./.eslintrc:/code/.eslintrc
    - ./.ssl:/code/.ssl
    - ./.stylelintrc:/code/.stylelintrc
    - ./bin:/code/bin
    - ./cogs-client.js:/code/cogs-client.js
    - ./cogs-server.js:/code/cogs-server.js
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./package.json:/code/package.json
    - ./src:/code/src
    - /code/build
    - /code/node_modules
  command: 'true'

dbdata:
  image: busybox:1.24.1
  volumes:
    - /var/lib/postgresql/data
  command: 'true'

postgres:
  image: postgres:9.4.5
  volumes_from:
    - dbdata

cogs-client: &shared
  image: *image
  volumes_from:
    - data
  environment:
    SIGNAL_URL: ws://docker:1337
  command: >
    bin/build-client -pw build/client/class-names.json,src/client,src/shared

cogs-server:
  <<: *shared
  command: bin/build-server -pw src/host,src/region,src/shared,src/signal

livereload:
  <<: *shared
  ports:
    - '35729:35729'
  command: bin/livereload

client:
  <<: *shared
  ports:
    - '80:80'
  command: nginx

signal:
  <<: *shared
  links:
    - postgres
  ports:
    - '1337:80'
  environment:
    CLIENT_URL: http://docker
    MAIL_ENABLED: 0
    REGION_URLS: http://docker:1338
  command: >
    node_modules/.bin/watchy -pw build/shared,build/signal -- node build/signal

# region:
#   <<: *shared
#   ports:
#     - '1338:1338'
#   command: >
#     node_modules/.bin/watchy -pw build/region,build/shared -- node build/region
