data:
  image: &image quay.io/turbocarclub/turbo-car-club:0.0.12
  volumes:
    - ./.eslintrc:/code/.eslintrc
    - ./.scss-lint.yml:/code/.scss-lint.yml
    - ./bin:/code/bin
    - ./cogs-client.js:/code/cogs-client.js
    - ./cogs-server.js:/code/cogs-server.js
    - ./Makefile:/code/Makefile
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./package.json:/code/package.json
    - ./src:/code/src
    - /code/build
    - /code/node_modules
    - /var/lib/postgresql/data
  command: 'true'

postgres:
  image: postgres:9.4.5
  volumes_from:
    - data
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  ports:
    - '5432'

nginx:
  image: nginx:1.9.5
  volumes_from:
    - data
  ports:
    - '80:80'

cogs-client: &shared
  image: *image
  volumes_from:
    - data
  environment:
    SIGNAL_URL: ws://docker:1337
  command: make cogs-client-w

cogs-server:
  <<: *shared
  command: make cogs-server-w

livereload:
  <<: *shared
  ports:
    - '35729:35729'
  command: bin/livereload

schema:
  <<: *shared
  environment:
    SOURCE: build/shared/data/schema.js
    TARGET_JSON: src/shared/data/schema.json
    TARGET_GRAPHQL: src/shared/data/schema.graphql
  command: make schema-w

signal:
  <<: *shared
  links:
    - postgres
  ports:
    - '1337:80'
  environment:
    KEY: foo
    MAIL_ENABLED: 0
    MAIL_FROM_NAME: Turbo Car Club
    MAIL_FROM_ADDRESS: support@turbocarclub.com
    POSTGRES_URL: pg://postgres:postgres@postgres/postgres
    CLIENT_URL: http://docker
  command: make signal-w

host:
  <<: *shared
  links:
    - signal
  ports:
    - '1338:80'
  environment:
    KEY: qrzeTOFGCcBcVmbnchSncrHo4sEpDDmVXSOof2WqoaRbWyJob3N0IiwxNDQ1Nzk4OTUzNTAyXSx7InVzZXJJZCI6MSwicmVnaW9uIjoiTG9jYWwiLCJuYW1lIjoiSG9zdCIsInVybCI6IndzOi8vZG9ja2VyOjEzMzgifV0=
    SIGNAL_URL: ws://signal
  command: make host-w
