data:
  image: &image quay.io/caseywebdev/turbo-car-club:ee4490944160a7b0c32bcf5e08cdf010cd436539
  volumes:
    - ./.eslintrc:/code/.eslintrc
    - ./.ssl:/code/.ssl
    - ./.stylelintrc:/code/.stylelintrc
    - ./bin:/code/bin
    - ./cogs-client.js:/code/cogs-client.js
    - ./cogs-server.js:/code/cogs-server.js
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./package.json:/code/package.json
    - ./src:/code/src
    - /code/build
    - /code/node_modules
  command: 'true'

dbdata:
  image: busybox:1.24.1
  volumes:
    - /var/lib/postgresql/data
  command: 'true'

postgres:
  image: postgres:9.4.5
  volumes_from:
    - dbdata

nginx:
  image: nginx:1.9.5
  volumes_from:
    - data
  ports:
    - '80:80'

cogs-client: &shared
  image: *image
  volumes_from:
    - data
  environment:
    SIGNAL_URL: wss://docker
  command: bin/build-client -pw build/client/class-names.json,src/client,src/shared

cogs-server:
  <<: *shared
  command: bin/build-server -pw src/host,src/shared,src/signal

livereload:
  <<: *shared
  ports:
    - '35729:35729'
  command: bin/livereload

signal:
  <<: *shared
  links:
    - postgres
  ports:
    - '443:443'
  environment:
    CLIENT_URL: http://docker
    MAIL_ENABLED: 0
  command: >
    node_modules/.bin/watchy -pw build/shared,build/signal -- node build/signal
