version: '2'

services:
  persisted-data:
    image: busybox:1.24.1
    volumes:
      - /etc/ssl/private
      - /var/lib/postgresql/data
    command: 'true'

  ephemeral-data:
    image: &image quay.io/caseywebdev/turbo-car-club:03aabea68efaae2127309e13a1c69664bbb4712d
    volumes:
      - ./.eslintrc:/code/.eslintrc
      - ./.stylelintrc:/code/.stylelintrc
      - ./bin:/code/bin
      - ./etc:/code/etc
      - ./package.json:/code/package.json
      - ./src:/code/src
      - /code/build
      - /code/node_modules
    command: 'true'

  consul:
    image: quay.io/caseywebdev/consul:971a22057648e734ad5ff8b494d3d842de74e793
    command: -dev

  postgres:
    image: quay.io/caseywebdev/postgres:4442cadfa34066f68add438cd644238f3c6db4a0
    volumes_from:
      - persisted-data
    links:
      - consul

  cogs: &shared
    image: *image
    volumes_from:
      - persisted-data
      - ephemeral-data
    command: bin/watch-build
    links:
      - consul

  livereload:
    <<: *shared
    command: bin/livereload

  lb:
    <<: *shared
    ports:
      - '80:80'
      - '443:443'
    environment:
      LIVERELOAD_SERVER_NAME: livereload.dev.turbocarclub.com
      LIVERELOAD_URL: https://livereload.dev.turbocarclub.com
      CONSUL_AUTH: foo:bar
      CONSUL_SERVER_NAME: consul.dev.turbocarclub.com
      SIGNAL_SERVER_NAME: signal.dev.turbocarclub.com
    command: bin/lb

  signal:
    <<: *shared
    command: bin/watch-signal
    links:
      - consul
      - postgres
