data:
  image: &image quay.io/caseywebdev/turbo-car-club:0bc9c7d1de524534b3b13ea18366e2f810412a05
  volumes:
    - ./.eslintrc:/code/.eslintrc
    - ./.stylelintrc:/code/.stylelintrc
    - ./bin:/code/bin
    - ./etc:/code/etc
    - ./package.json:/code/package.json
    - ./src:/code/src
    - /code/build
    - /code/node_modules
  command: 'true'

dbdata:
  image: busybox:1.24.1
  volumes:
    - /var/lib/postgresql/data
  command: 'true'

consul:
  image: consul:v0.6.4
  ports:
    - '8500:8500'
    - '53:8600/udp'
  command: >
    agent
    -dev
    -client 0.0.0.0
    -dc dev
    -recursor 8.8.8.8
    -recursor 8.8.4.4

postgres:
  image: postgres:9.4.5
  volumes_from:
    - dbdata

cogs-client: &shared
  image: *image
  volumes_from:
    - data
  environment:
    CLIENT_URL: http://www.turbocarclub.com.dev
    SIGNAL_URL: ws://signal.turbocarclub.com.dev
    SIGNAL_SERVER_NAME: signal.turbocarclub.com.dev
  command: bin/watch-build-client

cogs-server:
  <<: *shared
  command: bin/watch-build-server

livereload:
  <<: *shared
  ports:
    - '35729:35729'
  command: bin/livereload

client:
  <<: *shared
  dns: 172.17.0.1
  ports:
    - '80:80'
  command: bin/client

signal:
  <<: *shared
  dns: 172.17.0.1
  links:
    - postgres
  environment:
    CLIENT_URL: http://www.turbocarclub.com.dev
    MAIL_ENABLED: 0
  command: bin/watch-signal

# region:
#   <<: *shared
#   ports:
#     - '1338:1338'
#   command: >
#     node_modules/.bin/watchy -pw build/region,build/shared -- node build/region
