app:
  image: quay.io/turbocarclub/turbo-car-club:0.0.3
  volumes:
    - ./tmp/build/client:/code/build/client
    - ./src:/code/src
    - ./.eslintrc:/code/.eslintrc
    - ./.scss-lint.yml:/code/.scss-lint.yml
    - ./cogs-client.js:/code/cogs-client.js
    - ./cogs-server.js:/code/cogs-server.js
    - ./Makefile:/code/Makefile
    - ./package.json:/code/package.json
  ports:
    - '1337:80'
    - '1338:8080'
  command: make dev

nginx:
  image: nginx:1.9.5
  volumes:
    - ./tmp/build/client:/usr/share/nginx/html
  ports:
    - '80:80'
