version: '3'

volumes:
  build:
  node-modules:
  pg-data:
  private:

services:
  consul:
    image: quay.io/caseywebdev/consul:971a22057648e734ad5ff8b494d3d842de74e793
    command: -dev

  postgres:
    image: quay.io/caseywebdev/postgres:4442cadfa34066f68add438cd644238f3c6db4a0
    volumes:
      - pg-data:/var/lib/postgresql/data
    depends_on:
      - consul

  cogs: &shared
    image: quay.io/caseywebdev/turbo-car-club:ba5b36080d7083720566df7a16e20e2cab213ba4
    volumes:
      - ./.eslintrc:/code/.eslintrc
      - ./.stylelintrc:/code/.stylelintrc
      - ./bin:/code/bin
      - ./etc:/code/etc
      - ./package.json:/code/package.json
      - ./src:/code/src
      - build:/code/build
      - node-modules:/code/node_modules
      - private:/etc/ssl/private
    command: bin/watch-build
    depends_on:
      - consul

  livereload:
    <<: *shared
    command: bin/livereload

  lb:
    <<: *shared
    ports:
      - '80:80'
      - '443:443'
    environment:
      LIVERELOAD_SERVER_NAME: livereload.dev.turbocarclub.com
      LIVERELOAD_URL: https://livereload.dev.turbocarclub.com
      CONSUL_AUTH: foo:bar
      CONSUL_SERVER_NAME: consul.dev.turbocarclub.com
      SIGNAL_SERVER_NAME: signal.dev.turbocarclub.com
    command: bin/lb

  signal:
    <<: *shared
    command: bin/watch-signal
    depends_on:
      - consul
      - postgres
