app:
  image: quay.io/turbocarclub/turbo-car-club:0.0.1
  volumes:
    - ./public/textures:/code/public/textures
    - ./public/index.html:/code/public/index.html
    - ./src:/code/src
    - ./.eslintrc:/code/.eslintrc
    - ./.scss-lint.yml:/code/.scss-lint.yml
    - ./cogs-client.js:/code/cogs-client.js
    - ./cogs-server.js:/code/cogs-server.js
    - ./Makefile:/code/Makefile
  working_dir: /code
  ports:
    - '80:80'
  environment:
    PORT: 80
  command: make dev
