version: '3'

volumes:
  build:
  pg-data:

services:
  # traefik:
  #   image: traefik:1.1.2
  #   volumes:
  #     - ./etc/traefik.tml:/etc/traefik/traefik.toml
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - '80:80'
  #     - '443:443'

  postgres:
    image: postgres:9.6.2
    volumes:
      - pg-data:/var/lib/postgresql/data

  cogs: &shared
    image: quay.io/caseywebdev/turbo-car-club:8b4cdad2234d025b8ac89ba0f91274683e87fd99
    volumes:
      - ./.eslintrc:/code/.eslintrc
      - ./.stylelintrc:/code/.stylelintrc
      - ./bin:/code/bin
      - ./etc:/code/etc
      - ./package.json:/code/package.json
      - ./src:/code/src
      - build:/code/build
    command: bin/watch-build

  livereload:
    <<: *shared
    command: bin/livereload

  client:
    <<: *shared
    environment:
      LIVERELOAD_URL: http://livereload.dev.turbocarclub.com
    command: bin/client

  signal:
    <<: *shared
    command: bin/watch-signal
    depends_on:
      - postgres
