apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
data:
  traefik.toml: |
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
    [acme]
      email = "c@sey.me"
      storageFile = "/mnt/traefik-data/acme.json"
      entryPoint = "https"
      [[acme.domains]]
        main = "turbocarclub.com"
        sans = ["www.turbocarclub.com", "signal.turbocarclub.com"]
    [kubernetes]
