apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: quay.io/caseywebdev/turbo-car-club:1687dd3d2b9ce0ed06874ea5882ed4f2f06cdb6f
        command: ["bin/client"]
        env:
        - name: CLIENT_URL
          value: https://www.turbocarclub.com
        - name: REGIONS
          value: uno=https://www.turbocarclub.com
        - name: SIGNAL_URL
          value: wss://signal.turbocarclub.com
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0
