apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: signal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: signal
    spec:
      containers:
      - name: signal
        image: quay.io/caseywebdev/turbo-car-club:1687dd3d2b9ce0ed06874ea5882ed4f2f06cdb6f
        command: ["bin/signal"]
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: accessKeyId
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: secretAccessKey
        - name: CLIENT_URL
          value: https://www.turbocarclub.com
        - name: KEY
          valueFrom:
            secretKeyRef:
              name: signal
              key: key
        - name: MAIL_ENABLED
          value: '1'
        - name: SIGNAL_URL
          value: wss://signal.turbocarclub.com
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0
