apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: signal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: signal
    spec:
      containers:
      - name: signal
        image: quay.io/caseywebdev/turbo-car-club:2c66a1278eb32de90dca4ca54a9b02b0710ca7c6
        command: ["bin/signal"]
        env:
        - name: CLIENT_URL
          value: https://www.turbocarclub.com
        - name: KEY
          valueFrom:
            secretKeyRef:
              name: signal
              key: key
        - name: MAIL_ENABLED
          value: '1'
        - name: SIGNAL_URL
          value: wss://signal.turbocarclub.com
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
