apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: signal.turbocarclub.com
    http:
      paths:
      - backend:
          serviceName: signal
          servicePort: 80
  - http:
      paths:
      - backend:
          serviceName: client
          servicePort: 80
